export enum SCREENS {
  HOME = '/',
  LOGIN = '/login',
  DASHBOARD = '/dashboard',
  PROJECTS = '/projects',
  CONTRACTORS = '/contractors',
  SUPPORT = '/support',
  BILLS = '/bills',
  PERFORMANCE = '/performance',
  REPORTS = '/reports',
  SHORTAGES = '/shortages',
  SHOP = '/shop',
  CREATE_PROJECT ='/create-project',
  OPS_ADMINISTRATION = '/ops',
  DETAIL = '/detail',
  PROFILE = '/profile',
  CONTRACTOR_DETAILS = '/contractor-detail',
  CHAT = '/chat',
  TODO = '/todo',
}