export enum SCREENS {
  HOME = '/',
  LOGIN = '/login',
  DASHBOARD = '/dashboard',
  PROJECTS = '/projects',
  CONTRACTORS = '/contractors',
  SUPPORT = '/support',
  BILLS = '/bills',
  PERFORMANCE = '/performance',
  REPORTS = '/reports',
  SHORTAGES = '/shortages',
  SHOP = '/shop',
  CREATE_PROJECT ='/create-project',
  OPS_ADMINISTRATION = '/ops',
  DETAIL = '/detail',
  PROFILE = '/profile',
  CONTRACTOR_DETAILS = '/contractor-detail',
  CHAT = '/chat',
  TODO = '/todo',
  APPS = '/apps',
  FILE_MANAGER = '/files',
  MAIL = '/mail',
  KANBAN = '/kanban',
  NUMBER_RANGES = '/number-ranges',
  BILLING_DETAILS = '/billing-details',
  TRADES = '/trades',
  DOCUMENTS = '/documents',
}

export const API_BASE_URL = 'https://magga-676xiecbma-uc.a.run.app';
export const CLIENT_BASE_URL = 'http://localhost:8080';